version: '3'
services:
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile.influxdb
    ports:
      - '8086:8086'
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    links:
      - influxdb
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_INSTALL_PLUGINS: "blackmirror1-singlestat-math-panel"
    ports:
      - '3000:3000'
  k6:
    image: loadimpact/k6
    ports:
      - '6565:6565'
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    command: 'version'
